### ISSUE TITLE
Actualizar el schema.md añadiendo campos de Listado de Órdenes del Congreso GTO

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/estandar-datos-legislativos#10]
#### Descripción

Actualizar el archivo [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) añadiendo los campos que aparecen en el endpoint de Listado de Órdenes del Congreso de Guanajuato.

#### ¿Qué hay que hacer?

En particular, hay que consumir el endpoint correspondiente y parser la respuesta en formato JSON, ver qué campos de la respuesta no se encuentran actualmente en el [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) y añadirlos.

#### Endpoint

Listado de Órdenes:
`GET http://www.congresogto.gob.mx/ordenes/ordenes_api.json`

**Comment by ponentesincausa** [comment]
cerrado con ordenes-schema commit d305230

**Comment by ponentesincausa** [comment]
hola, este tampoco es el campo que dice, veo que es:

```
` Belongs to` **[Comision](#Comisiones)**
` Belongs to` **[Legislatura](#Legislaturas)**
  * fecha
  * ejercicio
  * archivo_pdf
  * tipo_de_orden (reunion, sesión solemne, diputación permanente, junta preparatoria, sesión extraordinaria)
```

y en el endpoint es:

```
id: numerico
fecha: fecha
descripcion: cadena
fondo: cadena
subfondo: cadena
seccion: cadena
clave: cadena
lugar: cadena
fecha_radicacion: ??
iniciante: ??
tipo_documento: numerico
asunto: cadena
comisiones: [ { comision:  { nombre: cadena } } ]
```
