### ISSUE TITLE
Actualizar el schema.md añadiendo campos del Detalle de la Orden/Reunión del Congreso GTO

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/estandar-datos-legislativos#11]
#### Descripción

Actualizar el archivo [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) añadiendo los campos que aparecen en el endpoint del Detalle de la Orden/Reunión del Congreso de Guanajuato.

#### ¿Qué hay que hacer?

En particular, hay que consumir el endpoint correspondiente y parser la respuesta en formato JSON, ver qué campos de la respuesta no se encuentran actualmente en el [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) y añadirlos.

#### Endpoint

Detalle de la Orden/Reunión:
`GET http://www.congresogto.gob.mx/ordenes/780/orden_api.json`

**Comment by ponentesincausa** [comment]
este me sale muy distinto a lo mergeado. ¿podemos checarlo, @carlitos ?

esto es lo commiteado: 

```
archivo
descripcion
numero_romano
colocacion(orden)
```

esto es lo que aparece en el endpoint: 

```
[{
"id":780,
"fecha":"2017-05-11",
"diputado":"DIPUTADA ARCELIA MAR\u00cdA GONZ\u00c1LEZ GONZ\u00c1LEZ",
"ejercicio":"Segundo A\u00f1o de Ejercicio Constitucional",
"periodo":"Segundo Periodo Ordinario",
"proyecto_orden":false,
"archivo_gaceta":{"url":"https://congresogto.s3.amazonaws.com/uploads/orden/archivo_gaceta/780/O.D._11_mayo_2017.pdf"}}]
```
