### ISSUE TITLE
Actualizar el schema.md añadiendo campos de Listado de Dictamenes en comisiones del Congreso GTO

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/estandar-datos-legislativos#12]
#### Descripción

Actualizar el archivo [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) añadiendo los campos que aparecen en el endpoint de Listado de Dictamenes en comisiones del Congreso de Guanajuato.

#### ¿Qué hay que hacer?

En particular, hay que consumir el endpoint correspondiente y parser la respuesta en formato JSON, ver qué campos de la respuesta no se encuentran actualmente en el [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) y añadirlos.

#### Endpoint

Listado de Dictamenes en comisiones:
`GET http://www.congresogto.gob.mx/dictamenes_comisiones/dictamenes_comisiones_api.json`

**Comment by ponentesincausa** [comment]
dictámenes en comisiones y dictámenes en pleno me imagino que se refieren al mismo objeto, pero cuál es la diferencia, @carlitos ?
