### ISSUE TITLE
Actualizar el schema.md añadiendo campos de Listado de Decretos del Congreso GTO

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/estandar-datos-legislativos#13]
#### Descripción

Actualizar el archivo [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) añadiendo los campos que aparecen en el endpoint de Listado de Decretos en comisiones del Congreso de Guanajuato.

#### ¿Qué hay que hacer?

En particular, hay que consumir el endpoint correspondiente y parser la respuesta en formato JSON, ver qué campos de la respuesta no se encuentran actualmente en el [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) y añadirlos.

#### Endpoint

Listado de Decretos:
`GET https://www.congresogto.gob.mx/decretos.json`

**Comment by ponentesincausa** [comment]
Lo committeado:
```
Has many Iniciativas Has many Votaciones Belongs to Legislatura

Titulo
Fecha de presentacion
Archivo
Numero de publicacion (Periodico oficial)
```

Lo que hay:

```
id:
archivo: { url: cadena }
clave: cadena
clave_int: 344
created_at: datetime
descripcion: cadena
dictamen_id: numerico
fecha: fecha
iniciativa_id: numerico
num_publicacion: numerico
parte: cadena
publicacion_archivo: { url: cadena }
publicacion_fecha: fecha
publicacion_info: ?? 
titulo: null
updated_at: datetime
variable_id: numerico
```
