### ISSUE TITLE
Actualizar el schema.md añadiendo campos de Cabilderos Personas Morales del Congreso GTO

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/estandar-datos-legislativos#16]
#### Descripción

Actualizar el archivo [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) añadiendo los campos que aparecen en el endpoint de Cabilderos Personas Morales del Congreso de Guanajuato.

#### ¿Qué hay que hacer?

En particular, hay que consumir el endpoint correspondiente y parser la respuesta en formato JSON, ver qué campos de la respuesta no se encuentran actualmente en el [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) y añadirlos.

#### Endpoint

Cabilderos Personas Morales:
`GET http://www.congresogto.gob.mx/cabildero_morales/personas_morales_api.json`

**Comment by jesuslerma** [comment]
Hola  voy a trabajar en este.
