### ISSUE TITLE
Scrapper de Diputados Federales

### ISSUE THREAD

**Issue by basicavisual** [CodeandoMexico/estandar-datos-legislativos#2]
Hacer un scrapper del sitio http://www.congreso.gob.mx/ con los datos de los diputados federales. Hasta ahorita hemos identificado estos datos:

- [x] Nombre
- [ ] Partido
- [x] Tipo de representación (distrito o circunscripción )
- [x] Número de distrito o circunscripción
- [ ] Escolaridad
- [ ] Trayectoria profesional
- [ ] Comisiones a las que pertenece
- [ ] Iniciativas presentadas y estatus ante el grupo (adherente, iniciante, en grupo, aprobadas, desechadas, atendidas, retiradas, pendientes)
- [ ] Iniciativa: Iniciativa, turno a comisión, sinopsis, trámite en el pleno
- [ ] Proposiciones presentadas y estatus ante el pleno (proponente, diversos grupos parlamentarios, de grupo, aprobadas, desechadas, atendidas, retiradas, pendientes)
- [ ] Propuesta: Proposición, turno a comisión, resolutivos del proponente, resolutivos aprobados, trámite
- [ ] Asistencias por período (scrapper aparte porque va a ser un pain in the rear)
- [ ] Votaciones por período (fecha, título de la votación, sentido del voto) (same)

**Comment by ponentesincausa** [comment]
https://github.com/CodeandoMexico/representantes-patito-2/tree/feature/federal_diputados
