### ISSUE TITLE
Actualizar el schema.md añadiendo campos de Listado de todas las Iniciativas del Congreso GTO

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/estandar-datos-legislativos#9]
#### Descripción

Actualizar el archivo [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) añadiendo los campos que aparecen en el endpoint de Listado de todas las Iniciativas del Congreso de Guanajuato.

#### ¿Qué hay que hacer?

En particular, hay que consumir el endpoint correspondiente y parser la respuesta en formato JSON, ver qué campos de la respuesta no se encuentran actualmente en el [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) y añadirlos.

#### Endpoint

Listado de todas las Iniciativas:
`GET http://www.congresogto.gob.mx/iniciativas/iniciativas_api.json`

**Comment by jcespinosa** [comment]
Voy a trabajar en ese issue
¿Podrían asignarmelo?

**Comment by jcespinosa** [comment]
#23
